### ISSUE TITLE
the example doesn't work for me

### ISSUE THREAD

**Issue by kubanekjiri** [hpwit/I2SClockLessLedDriveresp32s3#3]
Hello,
I have configuration:
#define NUMSTRIPS 8
#define NUM_LEDS_PER_STRIP 60

#define EXAMPLE_PIN_NUM_DATA0 26  // B0
#define EXAMPLE_PIN_NUM_DATA1 47  // B1
#define EXAMPLE_PIN_NUM_DATA2 48  // B2
#define EXAMPLE_PIN_NUM_DATA3 38  // B3
#define EXAMPLE_PIN_NUM_DATA4 39  // B4
#define EXAMPLE_PIN_NUM_DATA5 40  // G0
#define EXAMPLE_PIN_NUM_DATA6 41  // G1
#define EXAMPLE_PIN_NUM_DATA7 42  // G2

doesn't work for me
![IMG_20230918_102339](https://github.com/hpwit/I2SClockLessLedDriveresp32s3/assets/145489294/64c9a704-2517-4103-adc8-4363b6b3815d)

Can I ask for help?

Arduino IDE 2.2.1
Board ESP32-S3 mini PS ram

Thank you

**Comment by hpwit** [comment]
Hello
can you show me the full code please
can you show me the serial output also
rgds
Yes

**Comment by kubanekjiri** [comment]
Hello,
serial output:
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a68
entry 0x403c98d4
[   322][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled

Full code:
[I2Sgettingstarted.txt](https://github.com/hpwit/I2SClockLessLedDriveresp32s3/files/12712949/I2Sgettingstarted.txt)

Arduino settings:
![obrazek](https://github.com/hpwit/I2SClockLessLedDriveresp32s3/assets/145489294/686e5275-92cc-4ade-92cb-c29e07601038)

Thank you very much.

**Comment by hpwit** [comment]
I will try the code to debug and let you know
rgd

**Comment by hpwit** [comment]
hello pin 26 doesn't exist  hence the reboot.?
I have took you code and run it on a normal esp32s3 only changing that pin it works
with 60 leds only you should add a delay in the loop
let me know
regards Yves

**Comment by kubanekjiri** [comment]
Hello, yes, that's right! SPI0/1: GPIO26-32 is usually used for SPI flash and PSRAM and is not recommended for other applications. My mistake :( Thank you very much for your help!!!!!

**Comment by hpwit** [comment]
no problem.
On my board these pins are not even exposed to me hence I couldn't even make the mistake :)
Let me know if it works well now.
and maybe a video.
I am happy that someone uses this driver , maybe I  will spend more time upgrading it

**Comment by kubanekjiri** [comment]
Hello, here is an example of using your library for 8x120 LEDs. I have already tried 8x960 LEDs and it works perfectly.
Great work, thank you!!!!!
https://uloz.to/file/DsJMDBNEC3Nb/vid-20230926-133129-mp4#!ZJZ4LmR2ZGt4AJV4AmNmMQR2MGtkZJWBZ0ZmIHb2YHqUEzZ3ZD==

**Comment by hpwit** [comment]
Hello
thank you for the video !! great build can I ask what are you gonna use it for ?
