### ISSUE TITLE
RGBW support

### ISSUE THREAD

**Issue by thomas6886** [hpwit/I2SClockLessLedDriveresp32s3#8]
Hi hpwit,

Thanks for the library, it works great with RGB leds. But now I would like to use it with RGBW leds, is there a way to achieve this? Please let me know!

Kind regards,

Thomas

**Comment by hpwit** [comment]
Thank you for using this library 
It's already compatible with  Rgbw 
I will write a simple example for it. 
Rgds
Yves

**Comment by thomas6886** [comment]
Alright! Thanks for the quick response, I'm looking forward to it.

Kind regards,

Thomas

**Comment by hpwit** [comment]
No issue can I ask you a bit more about your build for which you're using this library if I may ask.

**Comment by hpwit** [comment]
reload the  library you have the example for the RGBW support and the Pixel object

**Comment by thomas6886** [comment]
Thanks for the quick example! I'll implement it now. 

Regarding the build, I'm building a custom led driver for decor pieces I make for different shows. In the past I used Teensy microcontrollers, but wanted to try something different with built-in WiFi/BLE for quick configuration.

Thanks again for the support.

Thomas

**Comment by hpwit** [comment]
Let me know if it works as planned 
Yves

**Comment by thomas6886** [comment]
It didn't work right away, but didn't have time to figure out what was wrong exactly. I'll get back to you asap.
